let sell_dict = {
  merch_keep: [
    "hpot0",
    "hpot1",
    "mpot0",
    "mpot1",
    "stand0",
    "tracker",
    "rod",
    "pickaxe",
    "offering",
    "scroll0",
    "scroll1",
    "scroll2",
    "cscroll0",
    "cscroll1",
    "cscroll2",
    "elixirluck", // 'jacko',
    "seashell",
    "computer",
    "egg0",
    "egg1",
    "egg2",
    "egg3",
    "egg4",
    "egg5",
    "egg6",
    "egg7",
    "egg8",

    // CRAFTING
    "essenceoffire",
    "feather0",

    // EXCHANGE
    "gemo0",
    "candycane",
    "mistletoe",
    "basketofeggs",
    "offeringp",
    // 'candy1', 'candy0',
  ],
  farmer_keep: [
    "hpot0",
    "hpot1",
    "mpot0",
    "mpot1",
    "tracker",
    "luckbooster",
    "jacko",
    "mshield",
    "sshield", // ! TODO: block sending loadout gear in unpack code instead
    // 'egg0', 'egg1', 'egg2', 'egg3', 'egg4', 'egg5', 'egg6', 'egg7', 'egg8',
  ],
  low: [
    "hpamulet",
    "hpbelt",
    "wattire",
    "wcap",
    "wbreeches",
    "wgloves",
    "stinger",
    "cclaw",
    "ringsj",
    "vitearring",
  ],
  toMerch: ["ringsj", "gem0", "gem1", "seashell"],
  merchSell: [
    "coat1",
    "helmet1",
    "hpbelt",
    "hpamulet",
    "whiteegg",
    "smoke",
    "phelmet",
    "gphelmet",
    "pants1",
    "gloves1",
    "shoes1",
    "pmaceofthedead",
    "warmscarf",
    "snowball",
    "wcap",
    "wshoes",
    "spear",
    "pstem",
    "frogt",
    "bandages",
    "smush",
    "dstones",
    "lspores",
    "slimestaff",
    "stinger",
    "mushroomstaff",
    "iceskates",
    "sword",

    "epyjamas",
    "carrotsword",
    "xmassweater",
  ], // 'xmasshoes', 'xmashat', 'eears', 'eslippers',
  merchTradeSell: [],
};
