let upBlackList = {
  2: ["vitring", "talkingskull"],
};
let upWhiteList = {
  upgrade_all: [
    "xmaspants",
    "xmashat",
    "xmasshoes", // 'xmassweater',
    "eslippers",
    "eears", // "epyjamas", "stinger", "swifty",
    "mittens",

    "wattire",
    "wbreeches",
    "wgloves",
    "wshoes",
    "wcap",
    "hbow",
    "sshield",
    "quiver",
    "cclaw",

    "ololipop",
    "glolipop",
    "broom",
    "wingedboots",
  ],
  high_upgrade_all: [
    // 'xmasshoes', 'xmaspants', 'xmassweater',
    // "quiver", "xmashat", "epyjamas", "eears",

    "ecape",
    "ornamentstaff",
    // 'staffofthedead', 'swordofthedead', // 'pmaceofthedead',
    "daggerofthedead", // 'bowofthedead', 'maceofthedead',
    "candycanesword",
    "bowofthedead",

    "oozingterror",
    "harbringer",
    "basher",
    "pinkie",
    "t2bow",
    "merry",
    "firestaff",
    "fireblade",
    "bataxe",
    "dagger",
    "tigerhelmet",
    "tigershield",
    "xmace",

    "firestars",
    "snowflakes",

    "hpants",
    "hgloves",
    "fierygloves",
    "pmace",
  ],
  compound: [
    "intamulet",
    "intring",
    "intbelt",
    "intearring",
    "strring",
    "strearring",
    "stramulet",
    "strbelt",
    "dexamulet",
    "dexring",
    "dexbelt",
    "dexearring",
    "skullamulet",
    "book0",
    "hpamulet",
    "hpbelt",
    "ringsj",
    "wbook0",
    "vitring",
    "jacko",
    "talkingskull",
    "vitearring",
    "rednose",
    "santasbelt",
    //'lantern',
  ],
};
