const itemsToBuy = [
  // INGREDIENTS
  "ink",
  "bfur",
  "snakeoil",
  "snakefang",
  "lotusf",
  "cscale",
  "ascale",
  "pleather",
  "poison",
  "spidersilk",
  "emptyheart",
  "feather0",
  "x0",
  "x1",
  "x2",
  "x3",
  "x4",
  "x5",
  "x6",
  "x7",
  "x8",
  "egg0",
  "egg1",
  "egg2",
  "egg3",
  "egg4",
  "egg5",
  "egg6",
  "egg7",
  "egg8",
  "feather0",
  "carrot",
  "feather1",
  "essenceoffrost",
  "essenceofgreed",
  "essenceoflife",
  "essenceoffire",
  "essenceofnature",
  "bwing",

  "offeringp",

  // EXCHANGE
  "mistletoe",
  "basketofeggs",
  "candycane",
  "leather",
  "goldenegg",
  "xbox",
  "5bucks",
  "troll",
  "candypop",
  "gift0",
  "gift1",
  "armorbox",
  "weaponbox",
  "candy0",
  "ornament",
  "gemfragment",
  // MISC
  "cryptkey",
  "cxjar",
  "emotionjar",
  "frozenkey",
  "funtoken",
  "monstertoken",
  "pvptoken",
  "luckscroll",
  "frequencyscroll",
  "xpscroll",
  "evasionscroll",
  "outputscroll",
  "critscroll",
  "lifestealscroll",
  "mbones",

  "merry",
  "t3bow",
  // "bowofthedead",
  "xmace",
  "crossbow",
  "pinkie",
  "ooze",
  "oozingterror",
  "cupid",
  "bataxe",
  "hbow",
  "cryptkey",
  // HEAD
  "xhelmet",
  "cyber",
  "fury",
  "oxhelmet",
  "tigerhelmet",
  "rednose",
  // LEGS
  "starkillers",
  "fallen",
  "xpants",
  // BODY
  "tshirt7",
  "tshirt4",
  "tshirt9",
  "tshirt8",
  "tshirt3",
  "tshirt88",
  "luckyt",
  "vattire",
  "cdragon",
  "warpvest",
  "xarmor",
  // BOOTS
  "wingedboots",
  "xboots",
  // GLOVES
  "wgloves",
  "fierygloves",
  "supermittens",
  "powerglove",
  "xgloves",
  "vgloves",
  "goldenpowerglove",
  "mpxgloves",
  "poker",
  // CAPES
  "gcape",
  "vcape",
  "stealthcape",
  "fcape",
  "angelwings",
  "tigercape",
  // RINGS
  "intring",
  "dexring",
  "strring",
  "cdarktristone",
  "cring",
  "resistancering",
  "armorring",
  "vring",
  "zapper",
  "ringhs",
  "trigger",
  "ringofluck",
  "goldring",
  "suckerpunch",
  "solitaire",
  // EARRINGS
  "strearring",
  "dexearring",
  "dexearringx",
  "lostearring",
  "cearring",
  "molesteeth",
  "mearring",
  "intearring",
  "vitearring",
  // AMULETS
  "amuletofm",
  "t2dexamulet",
  "t2intamulet",
  "t2stramulet",
  "snring",
  "bfangamulet",
  "sanguine",
  "mpxamulet",
  "northstar",
  "dexamulet",
  "stramulet",
  "intamulet",
  // BELTS
  "mpxbelt",
  "sbelt",
  "santabelt",
  "mbelt",
  "dexbelt",
  "strbelt",
  "intbelt",
  // ORBS
  "talkingskull",
  "orbofsc",
  "ftrinket",
  "jacko",
  "charmer",
  "rabbitsfoot",
  "tigerstone",
  "orbg",
  "vorb",
  "orbofdex",
  "orbofint",
  "orbofstr",
  // WEAPONS
  "vhammer",
  "broom",
  "rod",
  "pickaxe",
  "firestaff",
  "fireblade",
  "pmace",
  "ololipop",
  "glolipop",
  "harpybow", //, 'throwingstars'
  // SHIELDS
  "sshield",
  "tigershield",
  "xshield",
  "mshield",
  // OFFHANDS
  "t2quiver",
  "wbook1",
  "wbookhs",
  "exoarm",

  "ecape",
  "eears",
  "epyjamas",
  "eslippers",

  "wbreeches", // 'wattire',

  "tracker",

  "vblood",
];
// "vitring",
// "candy1",

const shinyBlackList = [
  "hpamulet",
  "hpbelt",
  "stinger",
  "mushroomstaff",
  "slimestaff",
  "warmscarf",
  "carrotsword", //'candycanesword',
  "shoes1",
  "gloves1",
  "pants1",
  "coat1",
  "helmet1",
  "gphelmet",
  "spear",
  "iceskates",
  "phelmet",
  // "eears",
  // "epyjamas",
  // "eslippers",
  // "xmasshoes",
  // "xmashat",
  // "xmaspants",
  // "xmasrobe",
  // "xmassweater",
];

function buyScrolls() {
  // if (!is_in_range('lucas')) return
  let scroll0_idx = locate_item("scroll0");
  let scroll1_idx = locate_item("scroll1");
  let scroll2_idx = locate_item("scroll2");
  let cscroll0_idx = locate_item("cscroll0");
  let cscroll1_idx = locate_item("cscroll1");

  if (scroll0_idx == -1 || character.items[scroll0_idx].q == 1)
    buy_with_gold("scroll0", 10);
  if (scroll1_idx == -1 || character.items[scroll1_idx].q == 1)
    buy_with_gold("scroll1", 10);
  if (scroll2_idx == -1 || character.items[scroll2_idx].q == 1)
    buy_with_gold("scroll2", 10);

  if (cscroll0_idx == -1 || character.items[cscroll0_idx].q == 1)
    buy_with_gold("cscroll0", 10);
  if (cscroll1_idx == -1 || character.items[cscroll1_idx].q == 1)
    buy_with_gold("cscroll1", 10);
}

module.exports = { itemsToBuy, shinyBlackList, buyScrolls };
